# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160414_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
    ]
