# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(to='movies.Director'),
        ),
        migrations.AlterField(
            model_name='director',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
