# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20160414_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='directors', to='movies.Movie'),
        ),
    ]
