# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20160415_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
