# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20160415_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
