# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20160415_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(to='movies.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
    ]
