# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20160415_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='companies',
            field=models.ManyToManyField(to='movies.Company'),
        ),
    ]
