# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20160415_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Company'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Director'),
        ),
    ]
