# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20160416_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie'),
        ),
    ]
