# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20160416_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='hola',
            field=models.TextField(default='hola'),
        ),
    ]
