# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_director_hola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='hola',
            field=models.TextField(default=''),
        ),
    ]
