# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20160428_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='hola',
        ),
        migrations.AddField(
            model_name='movie',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stateOrProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='zipCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
