# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_auto_20160428_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityname',
            new_name='city_name',
        ),
    ]
