# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20160428_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zipCode',
        ),
    ]
