# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_remove_city_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie_name',
        ),
    ]
