# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_auto_20160428_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
