# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_auto_20160501_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cities',
            field=models.ManyToManyField(blank=True, to='movies.City'),
        ),
    ]
